spring.application.name=ajedrez3d
server.port=8081
spring.mvc.problemdetails.enabled=true

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/ajedrez3d
spring.datasource.username=postgres
spring.datasource.password=4937
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect